name: Test

on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
    
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: yarn
    - name: Run tests
      run: yarn test
    - name: Lighthouse Test
      uses: treosh/lighthouse-ci-action@v7
      with:
        configPath: './lighthouserc.json'
    

